Irys-xyz/irys

- crates/actors/src/mining.rs
- crates/actors/src/vdf_service.rs
- crates/chain/src/chain.rs
This PR adds:
- VdfState to partition mining actor
- skip_to logic to skip to latest step count when a partition lags >3 steps behind
> Fix lagging mining process

- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/reth_service.rs
- crates/chain/src/chain.rs
This PR:
- Improves the RethServiceActor Fork choice update logic
> feat: Improve reth service FCU logic, add extra debug logs

- crates/actors/src/block_producer.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/packing.rs
- crates/actors/src/reth_service.rs
- crates/actors/src/validation_service.rs
- crates/efficient-sampling/src/lib.rs
Remove warnings from actors crate
> Remove warnings from actors crate

- Cargo.lock
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/packing.rs
- crates/api-server/src/routes/get_chunk.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/api.rs
- crates/chain/tests/api/external_api.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/utils.rs
- crates/database/src/database.rs
- crates/database/src/db_cache.rs
- crates/database/src/submodule/tables.rs
- crates/packing/src/lib.rs
- crates/reth-node-bridge/src/precompile/read_bytes.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
- crates/storage/tests/storage_module_index_tests.rs
- crates/types/Cargo.toml
- crates/types/src/chunk.rs
- crates/types/src/storage.rs
Local copy of the varun/types branch for CI.
* feat: conversion- TxChunkOffset,BlockChunkOffset,RelativeChunkOffset
* feat: conversion- PartitionChunkOffset
* feat: conversion- LedgerChunkOffset
* fix: impl Deref + derive-more
* cleanup + resolved comments
---------
> feat: Wrapper types for offsets + intervals (#215)

- crates/primitives/src/range_specifier.rs
Update alloy, reth, and revm submodules to versions without warnings.
> chore: update alloy, reth, and revm submodules

- crates/reth-node-bridge/src/genesis.rs
- crates/reth-node-bridge/src/node.rs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- crates/actors/src/packing.rs
- crates/types/src/config.rs
Added `packing` specific config fields to the `Config` object
Ref #243 
**Checklist**
> feat: add packing specific config

- crates/actors/src/epoch_service.rs
Fixes partition expiration test, adds just expired partition to the assert for new assigned slots partitions
> feat: fix partition expiration test

- crates/api-server/src/routes/get_chunk.rs
- crates/api-server/src/routes/network_config.rs
- crates/api-server/src/routes/peer_list.rs
- crates/api-server/src/routes/post_chunk.rs
- crates/api-server/src/routes/post_version.rs
- crates/chain/tests/api/external_api.rs
Fixes some of the json endpoints and adds tests for them.
#285 #286
**Checklist**
This is only meant to be a quick improvement and to show multiple endpoints can be checked. It is not refined.
> fix: fix/set endpoints content type to json

- crates/api-server/src/lib.rs
- crates/api-server/src/routes/block_index.rs
- crates/api-server/src/routes/mod.rs
- crates/chain/tests/api/external_api.rs
- crates/database/src/block_index_data.rs
- add endpoint for peers to sync block_index.
- add test of endpoint and its parameters
#286 
**Checklist**
the testing is not exhaustive and should be looked at in more detail in a future PR
> feat: add endpoint for peers to sync block_index

- crates/database/src/database.rs
- crates/database/src/tables.rs
Adds the ability to get/put Commitment Transactions in the nodes DB (including a sanity test).
Contributes to step 2 in [#292](https://github.com/Irys-xyz/irys/issues/292)
**Checklist**
Next step: Adding a commitments blocklane to the block headers
> feat: add commitment tx table to mdbx and add get/set functions

- crates/actors/src/epoch_service.rs
* Adds a `GetCommitmentStateGuardMessage` to retrieve a read only view of the commitments state
* Removes the `GetGenesisStorageModulesMessage` which is deprecated
resolves #323
**Checklist**
> feat: add commitments readguard, remove deprecated message

- Cargo.lock
- crates/storage/Cargo.toml
- crates/storage/src/storage_module.rs
This PR upstreams a hotfix made to Testnet to use atomic interval file writes to prevent corruption.
> feat: upstream the Atomic interval file fix

- crates/actors/src/broadcast_mining_service.rs
- crates/actors/src/mining.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/chain/src/chain.rs
Pass initial difficulty to miners to fix late subscription to difficulty updates broadcasting.
[Slack discussion](https://irys-xyz.slack.com/archives/C073VP1K05V/p1744930510721959)
> fix: pass initial difficulty to miners to fix late subscription to difficulty updates

- crates/actors/src/addresses.rs
- crates/actors/src/block_index_service.rs
- crates/actors/src/epoch_service/commitment_state.rs
- crates/actors/src/epoch_service/epoch_replay_data.rs
- crates/actors/src/epoch_service/epoch_service.rs
- crates/actors/src/epoch_service/epoch_service_config.rs
- crates/actors/src/epoch_service/epoch_service_messages.rs
- crates/actors/src/epoch_service/mod.rs
- crates/actors/src/epoch_service/partition_assignments.rs
- crates/actors/src/lib.rs
- crates/chain/src/chain.rs
- crates/database/src/block_index_data.rs
- Modularized epoch_service.rs by moving types and messages to dedicated files
- Added `EpochReplayData` initialization from database and block index
- Refactored chain.rs initialization sequence to use new methods
- Created separate files for cleaner code organization
- Added utility methods to load epoch data from database
- Updated init process with commitment replay support
> feat: epoch service code organization & initialization improvements

- crates/chain/src/chain.rs
- crates/reth-node-bridge/src/launcher.rs
- crates/reth-node-bridge/src/node.rs
this PR adds a retry to initialising the reth thread, with a single retry being expected in cases where reth needs to unwind some blocks
> feat: retry starting reth

- crates/chain/tests/multi_node/sync_chain_state.rs
Removes hardcoded ports in the file `sync_chain_state.rs` specifically in the function `init_configs()` and replaces with dynamically allocated ports.
#367 
**Checklist**
> feat: use dynamic ports in `sync_chain_state`

- crates/chain/tests/api/tx_commitments.rs
- crates/types/src/config.rs
Use a builder pattern to simplify genesis peer config in test
**Checklist**
> feat: simplify config of the genesis peer in tests

- crates/chain/tests/multi_node/peer_mining.rs
- crates/chain/tests/utils.rs
adding the `wait_for_mempoo()` test utility fn
**Checklist**
> feat: add wait_for_mempool util function

- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/types/src/block.rs
Sign blocks and validate block signatures during pre-validation
> feat: add block signing and validation

- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/multi_node/mod.rs
- crates/chain/tests/utils.rs
- crates/storage/src/storage_module.rs
- crates/testing-utils/src/utils.rs
Adds a `fork_recovery_test`
**Checklist**
> feat: add a fork_recovery_test

- README.md
Recently ran into an "open file limit" onm MacOS. This is a workaround.
> docs: to increase MacOS file limits

- Cargo.toml
- crates/actors/src/block_validation.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/storage_module_service.rs
- crates/actors/src/validation_service.rs
- crates/api-server/src/lib.rs
- crates/chain/src/chain.rs
- crates/chain/src/main.rs
- crates/chain/tests/api/external_api.rs
- crates/chain/tests/api/pricing_endpoint.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/block_production/testing_primitives.rs
- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/multi_node/sync_chain_state.rs
- crates/chain/tests/startup/startup.rs
- crates/chain/tests/utils.rs
- crates/p2p/src/tests/integration/mod.rs
- crates/p2p/src/tests/util.rs
- crates/vdf/src/state.rs
- crates/vdf/src/vdf.rs
- crates/vdf/src/vdf_utils.rs
This PR enables & makes the required changes for the [unused-async clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#unused_async)
> chore: enable unused-async clippy lint

- crates/actors/src/mempool_service.rs
move data transactions to index on block migration
> feat: move data transactions to index in handle_block_migrated()

- crates/actors/src/block_discovery.rs
Part of the mempool series of PRs.
This `adds get_data_tx_in_parallel()` to accompany the existing `get_commitment_tx_in_parallel()`
> feat: add get_data_tx_in_parallel() to block discovery service

- crates/actors/src/block_producer.rs
- crates/database/src/block_index_data.rs
Upstreams a couple misc tweaks:
- Adds an explicit sync_all call when we write to the block_index to help prevent partial writes.
- Add a EVM block hash validation check bypass for the genesis block, with a TODO & an improved error message.
> feat: upstream some tweaks made on the deployment/testnet branch

- crates/actors/src/block_validation.rs
- crates/actors/src/validation_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/block_production/reset_seed.rs
- crates/testing-utils/src/utils.rs
- crates/vdf/src/lib.rs
- crates/vdf/src/state.rs
- crates/vdf/src/vdf.rs
A clear and concise description of what the bug fix, feature, or improvement is.
**Checklist**
> fix: incorrect division in the VDF thread

- crates/api-server/src/routes/post_version.rs
- crates/chain/tests/api/client.rs
- crates/chain/tests/multi_node/peer_discovery.rs
- crates/p2p/src/peer_list.rs
- crates/types/src/irys.rs
- crates/types/src/peer_list.rs
- crates/types/src/version.rs
This PR implements p2p handshake signing
**Checklist**
> feat: implement version request signature

- crates/actors/src/addresses.rs
- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/services.rs
- crates/chain/src/chain.rs
- crates/chain/tests/utils.rs
This PR converts the BlockDiscoveryActor into a Tokio-style service
**Checklist**
> feat: block discovery conversion

- crates/p2p/src/sync.rs
This PR adds retries for fetching target height during the trusted sync
**Checklist**
> feat: add a retry logic for fetching target height during the trusted sync

- crates/types/src/difficulty_adjustment_config.rs
Two changes here:
Have the `adjust_difficulty()` function not truncate the precision of the adjustment calculation when actual time > target time. (adjusting difficulty down).
Update the adjustment tests to account for and validate smaller downward adjustments.
fixes: https://github.com/orgs/Irys-xyz/projects/5/views/7?pane=issue&itemId=116067326
> fix: difficulty adjustment no longer truncates precision on small adjustments

- crates/actors/src/block_validation.rs
validate block height = parent block height + 1
**Checklist**
> fix: validate block height = parent block height + 1

- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/mining.rs
- crates/actors/tests/chunk_migration_test.rs
- crates/chain/tests/block_production/block_production.rs
- crates/config/src/chain/chainspec.rs
- crates/types/src/block.rs
- crates/types/src/block_production.rs
remove recall_chunk_index as it is not used
**Checklist**
> chore: remove recall_chunk_index as it is not used

- crates/actors/src/block_validation.rs
- crates/actors/tests/block_validation_tests.rs
- crates/types/src/merkle.rs
- Add test for `poa_is_valid()`
- Add offset fix, improve checks
**Checklist**
> fix: Incorrect chunk offset validation

- crates/p2p/src/peer_network_service.rs
- Rather than ask a peer 5 times, and then ask the next peer 5 times etc, this now cycles through the peer list 5 times, asking each peer once per cycle.
- Should sync faster and not spam individual peers.
**Checklist**
> fix: iterate over full peers list up to 5 times instead of spamming each peer

- crates/actors/src/block_index_service.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/cache_service.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/reth_service.rs
- crates/actors/tests/chunk_migration_test.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/p2p/src/block_pool.rs
- crates/p2p/src/tests/block_pool/mod.rs
- crates/p2p/src/tests/util.rs
- remove duplication. cleaner logic.
- remove the term finalized
**Checklist**
> fix: tidier logic to retrieve finalized_height

- crates/types/src/difficulty_adjustment_config.rs
Before this PR: The difficulty adjustment mechanism only considered the minimum threshold when determining whether to adjust difficulty. This could lead to unbounded difficulty adjustments when the actual block time deviates significantly from the target block time.
This PR: Adds an upper bound to the difficulty adjustment calculation by introducing a maximum threshold check. The adjustment now only occurs when the percentage difference falls within the configured range (between the minimum and maximum thresholds). Specifically:
- Introduces max_threshold calculation from the existing max_difficulty_adjustment_factor configuration
- Updates the is_adjusted condition to check that percent_diff is both less than or equal to max_threshold AND greater than …
> fix: added upper bound to calculate difficulty

- crates/p2p/src/chain_sync.rs
This PR adds an indirect timeout to block validation
**Checklist**
> fix: timeout for block processing

- crates/chain/src/chain.rs
- crates/p2p/src/block_pool.rs
- crates/p2p/src/chain_sync.rs
- crates/p2p/src/tests/block_pool/mod.rs
This PR also adds missing payload repair to the periodic sync check
**Checklist**
> fix: attempt to repair missing payloads during catchup

- Cargo.lock
- crates/p2p/Cargo.toml
- crates/p2p/src/gossip_client.rs
This PR allows better log and tracing of unexpected peer responses by adding more granular error handling for `GossipClient`
**Checklist**
> feat: better unexpected error handling in gossip client

- crates/domain/src/models/storage_module.rs
This PR adds code to handle the case where the expected partition assignment information is out of date with the on-disk info on startup; whether the information is a.) new (nothing on disk), b.) an update ( i.e a capacity -> data assignment change), or c.) a conflict (mismatched existing parameters)
**Checklist**
> feat: improve packing param handling on SM initialisation

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/data_sync_service/chunk_orchestrator.rs
- crates/actors/src/mempool_service/commitment_txs.rs
In light of recent lock issues across awaits, follow the same pattern (tight scope) elsewhere in the codebase to avoid future debugging.
Note that none of the changes in this PR are current locking issues, this is more of a preventative measure.
https://github.com/Irys-xyz/irys/pull/734
**Checklist**
> chore: scope locks

- crates/chain/tests/multi_node/ema_forks.rs
- crates/chain/tests/multi_node/peer_discovery.rs
- crates/domain/src/models/peer_list.rs
- crates/p2p/src/gossip_client.rs
- crates/p2p/src/peer_network_service.rs
- crates/p2p/src/server.rs
- crates/p2p/src/types.rs
This PR enhances p2p health checks and rejection handling
**Checklist**
> feat: better healthcheck and rejection handling

- .github/workflows/flaky.yml
This PR adds a flaky test workflow on a schedule to run every night and monitor flaky tests. 
**Checklist**
> ci(flaky tests): added gh workflow on schedule to monitor flaky tests

- crates/domain/src/models/block_tree.rs
Fixes a longstanding bug where the block_tree could mark a fork block as tip making it out of sync with the canonical chain. Now this operation succeeds with `Ok(false)` and doesn't move the current canonical tip.
> fix: don't move the tip to a fork if it's not canonical

- .github/actions/setup-repo/action.yaml
The previous setup action used stable which could deviate from the toolchain version in the repo.  This action will use the toolchain from the file
**Checklist**
> ci(setup): use action that respects the repo toolchain file

- crates/actors/src/block_discovery.rs
- Remove remaining parts of BlockDiscovery actix actor from the tokio refactor PR https://github.com/Irys-xyz/irys/pull/585
**Checklist**
> chore: remove remaining parts of BlockDiscovery actix

- crates/actors/src/cache_service.rs
- crates/database/src/tables.rs
Removes currently unused PD tables
Once we have a better idea of the PD data model we'll re-add these
> feat: remove unused PD database tables

- crates/api-server/src/lib.rs
- crates/api-server/src/routes/index.rs
- crates/types/src/version.rs
A clear and concise description of what the bug fix, feature, or improvement is.
**Checklist**
> feat: add uptime_secs to /v1/info

- crates/domain/src/models/peer_list.rs
- crates/p2p/src/gossip_client.rs
- crates/p2p/src/gossip_data_handler.rs
- e2efdae Reverts https://github.com/Irys-xyz/irys/pull/812
- 4617695 Remove ScoreIncreaseReason::ValidData
https://github.com/Irys-xyz/irys/pull/812
**Checklist**
> fix: remove ScoreIncreaseReason::ValidData

- Cargo.lock
- crates/actors/src/block_validation.rs
- crates/irys-reth/Cargo.toml
- crates/irys-reth/src/evm.rs
- crates/irys-reth/src/lib.rs
- crates/irys-reth/src/shadow_tx.rs
sanitize shadow tx decoding into one place
**Checklist**
> feat: sanitize shadow tx decoding into one place
