Irys-xyz/irys

- Cargo.lock
- crates/actors/src/block_index_service.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/lib.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/packing.rs
- crates/actors/src/reth_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/config/src/chain/chainspec.rs
- crates/reth-node-bridge/src/adapter/engine_api.rs
- crates/reth-node-bridge/src/node.rs
This PR:
- Adds a new `RethServiceActor`, which handles forwarding fork choice updates to Reth.
- Improves error logging & _**adds code to cause critical actors to stop the process if they error**_ (block production and Reth).
- Hooks into block tree logic to update Reth in lockstep.
- Fixes a process restart losing head blocks (tweaks Reth side persistence values).
- Improves error logs.
> Feat: Overhaul Reth forkchoice logic

- crates/actors/src/mempool_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/packing.rs
- crates/actors/tests/chunk_migration_test.rs
- crates/chain/tests/api/external_api.rs
- crates/config/src/lib.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
- crates/storage/tests/storage_module_index_tests.rs
This is the promised fixup after testnet migration.
* Remove code related to migrating configs to the new format.
* Remove the now unused `initialize_storage_fies()` function
* patch up the tests that referenced it.
Note: The tests that require a wallet to be funded still fail because of that error.
My favorite part of this PR:
less code!
> Clean up configs 

- crates/actors/src/epoch_service.rs
- crates/database/src/data_ledger.rs
Complete the decoupling of ledgers from using `Ledger::` enum discriminants as an index and instead us them as an `id` that searches the list of active term ledgers.
This branch is based on https://github.com/Irys-xyz/irys/pull/163 and should be merged after it.
> Ledger state indexing

- crates/actors/src/mining.rs
- crates/database/src/database.rs
- crates/database/src/tables.rs
- crates/efficient-sampling/src/lib.rs
- crates/storage/tests/storage_module_index_tests.rs
This PR removes the unused PartitionHashesByDataRoot table, as well as it's associated DB methods and the one place in the one test that used it (the test passes with these modifications)
closes #85
> feat: remove the unused PartitionHashesByDataRoot table

- crates/actors/src/epoch_service.rs
- crates/actors/src/mining.rs
- crates/chain/src/chain.rs
- crates/chain/tests/block_production/basic_contract.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/block_production/mod.rs
- crates/config/src/lib.rs
- crates/database/src/database.rs
- crates/debug-utils/src/db.rs
- crates/reth-node-bridge/src/launcher.rs
- crates/storage/src/storage_module.rs
- crates/vdf/src/lib.rs
This PR:
- "demotes" StorageSubmoduleConfig from a LazyStatic to a regular struct, this is so we can reliably pass through the instance directory.
Closes #196
> fix: StorageSubmoduleConfig initialisation

- crates/chain/src/chain.rs
- crates/config/src/lib.rs
- crates/reth-node-bridge/src/node.rs
This PR is a small tweak to how instance directories work - instance_number is now optional, and a none value will forego creating a subdirectory at all.
> feat: allow production instances to forego the instance subdirectory

- .config/nextest.toml
- crates/chain/tests/api/api.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/block_production/basic_contract.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/block_production/external_tx.rs
- crates/chain/tests/block_production/mod.rs
- crates/chain/tests/integration/mod.rs
- crates/chain/tests/mod.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/chain/tests/programmable_data/mod.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/promotion/mod.rs
- crates/config/src/lib.rs
This PR:
- Creates a nextest configuration, with groups defined for `serial` tests (for now just tests that initialize reth/a full Irys node)
- Fixes some broken tests, disables a couple more busted tests (notablly the API e2e tests, which are broken due to the addition of balance checks)
> Feat: initial nextest integration

- .github/workflows/rust.yml
- crates/types/src/signature.rs
- crates/types/src/transaction.rs
This PR:
- Updates signature fixtures to use the new chainID
- fixes RLP and serde encoding for the internal ingress_proofs value
> fix: Transaction header signatures

- crates/actors/src/epoch_service.rs
Remove epoch blocks loop in epoch service initialization as we are still not generation NewEpochMessages messages
> Do not loop through epoch blocks, just zero first one

- crates/reth-node-bridge/src/adapter/engine_api.rs
- crates/reth-node-bridge/src/node.rs
- crates/reth-node-bridge/src/precompile/read_bytes.rs
Removed `cargo c` warnings from reth-node-bridge crate.
> Remove warnings from reth-node-bridge crate

- Cargo.lock
- Cargo.toml
- crates/storage-pricing/Cargo.toml
- crates/storage-pricing/src/lib.rs
#180 
This PR adds a standalone crate under `/crates/storage-pricing` for doing all the necessary calculations for:
- the operational cost of storing _n_ bytes of data
- network fees for storing data that the user has to pay
- EMA for the Irys token price (denominated in USD) that are to be stored in the block headers (storing this data will be added in a future PR)
- piggybacking extra lints that have been added to the root Cargo.toml 🙈 
This PR **does not** add any functionality to the node itself. 
All linter checks pass for `cargo clippy -p storage-pricing`
> feat: storage pricing module

- crates/chain/tests/block_production/block_production.rs
This PR aims to resolve the flaky serial_mine_ten_blocks test by increasing the wait timeout for new solutions. This is required due to the CI server having lower than expected single thread performance, which limits mining solution generation speeds vs the timeout, which is wall clock time based.
This PR is also coupled with a small tweak to the CI container configuration, so that each container has an enforced equal claim to the host's CPU time.
> Fix: flaky block production test

- crates/actors/src/block_validation.rs
- crates/types/src/difficulty_adjustment_config.rs
Ref #206 
Checks made in `difficulty_is_valid` are in this order now:
- check if difficulty is equal to calculated difficulty, else return error
- if `stats` is some, that implies the difficulty has beed adjusted
- if so, it checks if the block.diff > previousBlock.diff
> fix:valid solutions based on head-1 difficulty

- .github/workflows/rust.yml
- crates/actors/src/block_validation.rs
- crates/c/src/capacity_cuda.rs
- crates/packing/src/lib.rs
nvidia checks were disabled in CI. Warnings have been fixed, and nvidia build re-enabled
NA
**Checklist**
> chore: reenable nvidia in cargo c and fix warnings

- crates/chain/tests/external/block_production.rs
- crates/types/src/ingress.rs
- crates/types/src/irys.rs
- crates/types/src/signature.rs
- crates/types/src/transaction.rs
Restricts `MAX_CHUNK_SIZE` to only inside `merkle`
#244 
**Checklist**
> feat: restrict MAX_CHUNK_SIZE to only in merkle

- .github/workflows/rust.yml
- README.md
- crates/types/src/storage.rs
- crates/types/src/version.rs
- Code examples within comments will now be checked in github actions. i.e. `cargo test --doc` would be run as part of the `cargo test docs` step in the `cargo-doc` job.
- Code examples now compile and run
https://github.com/Irys-xyz/reth/pull/17/
**Checklist**
The macro that was causing the `cargo test --doc` compile failure https://github.com/Irys-xyz/reth/pull/17/
> test: test/compile code examples as PR check

- crates/api-server/src/lib.rs
- crates/api-server/src/routes/index.rs
- crates/chain/tests/api/external_api.rs
- crates/chain/tests/api/mod.rs
Test now runs local node. Checks:
1) /v1/info endpoint returns 200
2) /v1/info endpoint content-type is of type json
3) /v1/info endpoint contains the new block_index_height field
4) advance blocks, /v1/info endpoint contains an increased block_index_height
https://github.com/Irys-xyz/irys/issues/285
**Checklist**
- I added json content-type to the endpoint. I can update the other endpoints as a small separate PR.
> feat: add block_index height to default "node info" endpoint

- crates/chain/src/arbiter_handle.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/external_api.rs
- crates/chain/tests/block_production/basic_contract.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/integration/cache_service.rs
- crates/chain/tests/multi_node/peer_discovery.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/startup/startup.rs
This PR:
- Adds a `StopGuard` to `IrysNodeCtx`, which will panic if it's dropped when the `IrysNodeCtx.stop()` method hasn't been called/awaited
- Names arbiter handles (this was a change I was using to debug this issue, thought it'd be useful to keep in)
**Checklist**
> feat: add a StopGuard to IrysNodeCtx

- .config/nextest.toml
- Cargo.lock
- crates/api-server/Cargo.toml
- crates/api-server/src/lib.rs
- crates/api-server/src/routes/block.rs
- crates/api-server/src/routes/proxy.rs
- crates/api-server/src/routes/tx.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/api.rs
- crates/chain/tests/api/external_api.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/block_production/basic_contract.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/ema_pricing/ema_pricing.rs
- crates/chain/tests/external/programmable_data_basic.rs
- crates/chain/tests/integration/cache_service.rs
- crates/chain/tests/multi_node/peer_discovery.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/startup/startup.rs
- crates/chain/tests/synchronization/mod.rs
- crates/chain/tests/utils.rs
- crates/reth-node-bridge/src/node.rs
- crates/testing-utils/src/utils.rs
- crates/types/src/config.rs
This PR:
- Enables port randomisation for our HttpServer
- Enables port randomisation for Reth
- Changes the RPC proxy to use the appropriate Reth URL
- Exposes `Config` as part of `IrysNodeCtx`
- Disables VDF core pinning for tests
- Assigns `serial` tests to the new `heavy` test group, which enables test parallelisation
Closes #256 
**Checklist**
> feat: port randomisation

- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/chunk_migration_service.rs
- crates/database/src/data_ledger.rs
- crates/database/src/lib.rs
- crates/database/src/system_ledger.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/tests/storage_module_index_tests.rs
- crates/types/src/block.rs
Adds a `system_ledgers` section to the `IrysBlockHeader` above the existing storage `ledgers` section. The `system_ledgers` list contains one or more system ledgers, including a `Commitment` ledger defined in this PR
This resolves [#291](https://github.com/Irys-xyz/irys/issues/291)
**Checklist**
Next up, populating the genesis block with the correct genesis commitments.
> feat: add system_ledgers to the IrysBlockHeader

- crates/actors/src/mempool_service.rs
- crates/storage/src/storage_module.rs
- crates/types/src/chunk.rs
This feature enhances support for a "pending writes" queue length of > 1, enabling writes to be striped to disk and minimizing fragmentation.
We've updated `read_chunks()`, `write_data_chunk()`, and `get_intervals()` to present the union of the pending writes queue and stored intervals. This makes pending writes transparent to `StorageModule` clients - they simply write chunks and read them back without needing knowledge of the underlying pending writes buffer.
This implementation allows us to experiment with different values for `config.min_writes_before_sync` to optimize for both minimizing fragmentation and maximizing reliability.
No issue for this work as it is discovered / unplanned.
**Checklist**
@antouhou is there …
> feat: support > 1 pending writes for StorageModules

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_index_service.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/vdf_service.rs
- crates/api-server/src/routes/get_chunk.rs
- crates/api-server/src/routes/price.rs
- crates/api-server/src/routes/tx.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/utils.rs
- crates/database/src/block_index_data.rs
- crates/database/src/data_ledger.rs
- crates/reth-node-bridge/src/precompile/read_bytes.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
- crates/storage/tests/storage_module_index_tests.rs
- crates/types/src/block.rs
Renaming the `ledgers` attribute of the `IrysBlockHeader` struct to `data_ledgers` for consistency with `system_ledgers`. Also rename the `Ledger` enum to `DataLedger`
None
**Checklist**
- [] Tests have been added/updated for the changes.
> feat: rename ledgers->data_ledgers for consistency

- crates/chain/src/chain.rs
- crates/types/src/config.rs
A very small PR, that adds explicit stop ordering to the Actix services/arbiters
it also reduces the target block time for tests to help speed things along
> fix: explicit service shutdown ordering

- crates/chain/tests/api/api.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/block_production/mod.rs
- crates/chain/tests/block_production/testing_primitives.rs
- crates/chain/tests/external/programmable_data_basic.rs
- crates/chain/tests/integration/cache_service.rs
- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/synchronization/mod.rs
- crates/chain/tests/utils.rs
- crates/database/src/block_index_data.rs
Starts to add basic testing primitives, and tries to refactor some of our tests following those primitives.
Renables [api end to end](https://github.com/Irys-xyz/irys/blob/00614f16b43ad6c4103df4437b95f845541207b4/crates/chain/tests/api/api.rs#L33) tests that are fixed and refactored.
Also add simple test just to show these primitives working together, for example in [async fn test_mine() {](https://github.com/Irys-xyz/irys/blob/00614f16b43ad6c4103df4437b95f845541207b4/crates/chain/tests/block_production/testing_primitives.rs#L27)
#270
**Checklist**
> test: mining height control testing primitives

- crates/actors/src/block_validation.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/packing.rs
- crates/api-server/src/lib.rs
- crates/chain/tests/api/api.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/integration/cache_service.rs
- crates/chain/tests/programmable_data/basic.rs
- crates/chain/tests/utils.rs
- crates/efficient-sampling/src/lib.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
- crates/storage/tests/storage_module_index_tests.rs
- crates/types/src/difficulty_adjustment_config.rs
Continue on prior works to improve safety of type casting.
https://github.com/Irys-xyz/irys/issues/81
**Checklist**
Supersedes and closes https://github.com/Irys-xyz/irys/pull/237
> feat: replace unsafe as u32 cast with safe conversions

- .config/nextest.toml
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/mining.rs
- crates/api-server/src/routes/post_chunk.rs
- crates/database/src/submodule/db.rs
- crates/database/src/submodule/tables.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
- crates/storage/tests/storage_module_index_tests.rs
This PR:
- Adds a new `DataSizeByDataRoot` submodule table, which stores a data_root -> data_size mapping.
- Adds the appropriate set/get DB helper functions for  `DataSizeByDataRoot`.
- Integrates into `StorageModule::index_transaction_data`, and backpropagates a new data_size arg to tests and the chunk migration service.
- Rennovates StorageModule::generate_full_chunk to fix incorrect logic & move it to use partition relative offsets as inputs.
- Updates ChunkProvider::get_chunk_by_data_root to pass through partition relative offsets.
- Updates appropriate tests, notably the storage module index tx_path_overlap_tests, where new assertion logic is added.
- Adds a threads-required = 1 configuration to all tests by default, to prevent heavy tests from starving & …
> feat: add data_root -> data_size submodule table

- Cargo.lock
- crates/api-server/Cargo.toml
- crates/api-server/src/lib.rs
- crates/api-server/src/routes/tx.rs
The response JSONS from the `/v1/tx/{txid}` endpoint now differentiate between Commitment and Storage Transactions, adding support for retrieving Commitment transactions
IrysTransactionHeader ( "type": "storage" )
```json
{
"type": "storage",
"id": "5VBR6jRtZMBWBvSXPb6nWsij5jC5fPYNfi5cxaNqaJTd",
"version": 0,
"anchor": "11111111111111111111111111111111",
"signer": "11111111111111111111",
"dataRoot": "11111111111111111111111111111111",
"dataSize": "0",
"termFee": "0",
"ledgerId": 0,
"chainId": "0",
"signature": "1111111111111111111111111111111111111111111111111111111111111111U",
"bundleFormat": null,
"permFee": null,
"ingressProofs": null
}
```
CommitmentTransaction ( "type": "commitment" )
```json
{
"type": "commitment",
"id": …
```
> feat: /tx endpoint supports returning Storage and Commitment tx

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/ema_service.rs
- xtask/src/main.rs
- block producer depends on EMA service being aware on the latest optimistic block (where full block validation has not yet completed)
- EMA service now has the concept of an "optimistic" and "canonical" chain that it keeps track of and reacts on
- "canonical" only calculates EMA for validated blocks
- "optimistic" also includes blocks that are scheduled for validation
- this change allows the block producer to keep producing blocks at a faster pace than the block index can keep verifying them
**Checklist**
> feat: ema service handles optimistic chain head

- crates/storage/tests/storage_module_index_tests.rs
- crates/types/src/chunk.rs
- crates/types/src/chunked.rs
- crates/types/src/ingress.rs
- crates/types/src/irys.rs
- crates/types/src/lib.rs
- crates/types/src/merkle.rs
- crates/types/src/transaction.rs
This PR mirrors the changes previously made to Ingress proof generation to support an error-passing iterator as a data source
**Checklist**
The logic to "bridge" a Vec<u8> data source into the expected Result<Vec<u8>> iterator (and the fact it takes ownership) isn't great, so I'd appreciate any ideas on how to make it better.
> feat: allow for transaction data to be an Iterator

- Cargo.lock
- crates/api-client/Cargo.toml
- crates/api-client/src/lib.rs
- crates/chain/Cargo.toml
- crates/chain/tests/api/client.rs
- crates/chain/tests/api/mod.rs
This PR fixes IrysApiClient not making requests due to the version prefix being added twice
**Checklist**
> feat: api client e2e tests

- crates/actors/src/block_validation.rs
This fixes a bug in the `discovery_service.solution_hash_is_valid()` check.
A valid solution is supposed to meet or exceed the difficulty of the previous block's `diff`.
The buggy version of this was referencing `previous_solution_diff` which is the incorrect property and always set to 0 as our block production doesn't set it yet.
No issue, just discovered while debugging.
**Checklist**
> fix: solution validation now checks correct difficulty value

- Cargo.lock
- crates/actors/src/peer_list_service.rs
- crates/api-client/Cargo.toml
- crates/api-client/src/lib.rs
- crates/chain/tests/api/client.rs
- crates/chain/tests/utils.rs
- crates/gossip-service/tests/util.rs
This PR fixes `IrysApiCleint` not returning a transaction as expected due to wrong encoding used for the request
**Checklist**
> fix: api client not returning transaction

- crates/actors/src/epoch_service.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/chain/src/chain.rs
- crates/database/src/data_ledger.rs
Fixed critical bug where submit ledger terms completion would incorrectly expire ALL partitions instead of only eligible ones.
https://github.com/Irys-xyz/irys/blob/ca1368fa530332951e5f83bc9884089a33b08c65/crates/database/src/data_ledger.rs#L85-L90
- The `slot.last_height` field (used to determine partition age) was never being set.
- As a result all slots had default `last_height` of 0, causing them to expire simultaneously.
- This included expiring the last active slot in the ledger.
- Added  recording of the epoch blocks height in `last_height` during slot allocation
- Implemented protection to prevent expiration of the last slot in a term ledger
- Updated tests to verify proper partition retention
```rust
// Collect indices of slots to expire
for (idx, slot) in …
```
> fix: never expire the last partition in a ledger, and only expired ones.

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_index_service.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/epoch_service.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/chain/src/chain.rs
- crates/types/src/block.rs
- **Relocated NewEpochMessage to block_discovery**:
- Now properly positioned for processing epoch blocks from all peers
- Improved messaging flow and responsibility boundaries
- **Enhanced block_producer functionality**:
- Fixed `last_epoch_hash` population in all blocks
- Added proper `previous_solution_hash` tracking
- **Simplified Epoch Service API**:
- Split initialization into two clear phases:
1. `initialize()` - Takes genesis information
2. `replay_epoch_data()` - Processes epoch blocks and commitments
- Removed database and block_index dependencies
- Streamlined slot growth calculations
- **Introduced EpochReplayData structure**:
```rust
pub struct EpochReplayData {
pub epoch_block: IrysBlockHeader,
pub commitments: Vec<CommitmentTransaction>,
}
```
- **Optimized partition …
> feat: simplify epoch service to not rely on db or block_index

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_index_service.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service/epoch_replay_data.rs
- crates/actors/src/vdf_service.rs
- crates/api-server/src/routes/block.rs
- crates/chain/tests/utils.rs
- crates/database/src/block_index_data.rs
- Modified `block_index.get_item()` to accept `u64` parameters instead of `usize`
- Implemented safe internal type conversion with overflow handling
- Eliminated repetitive casting at call sites throughout the codebase
- Improves code readability by removing numerous explicit casts
- Centralizes conversion logic in one location
- Adds safety checks to prevent silent truncation on platforms where usize < u64
- Maintains API consistency with block heights represented as u64 elsewhere
```rust
// Before:
pub fn get_item(&self, index: usize) -> Option<&BlockIndexItem> {
self.items.get(index)
}
// After:
pub fn get_item(&self, block_height: u64) -> Option<&BlockIndexItem> {
// Check if block_height can fit into a usize
let index = if block_height <= usize::MAX as u64 {
block_height as usize
} …
```
> fix: refactor BlockIndex.get_item method signature

- crates/api-server/src/lib.rs
- crates/api-server/src/routes/tx.rs
This is a small PR that adds a (temporary until we have a gateway) `/tx/<txId>/is_promoted` route that signals if a given transaction a.) exists (by response code, 404 or 200) and b.) if it's promoted (by response body)
The primary use case for this is the Bundler node, which needs a mechanism for quickly checking on transaction status.
> feat: is_promoted HTTP route

- crates/actors/src/block_producer.rs
- crates/actors/src/commitment_cache.rs
- crates/actors/src/lib.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/services.rs
- crates/api-server/src/lib.rs
- crates/api-server/src/routes/commitment.rs
- crates/api-server/src/routes/mod.rs
- crates/api-server/src/routes/tx.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/mod.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/types/src/transaction.rs
This PR introduces commitment transaction ingress handling to the node:
* Creates a dedicated `CommitmentCache` service for tracking stakes and pledges, implementing the "new style" channel-based architecture
* Adds complete API support via the `/commitment_tx` route
* Implements the `CommitmentTxIngress` message handler for broadcasting new commitment transactions to the mempool
* Refactors shared validation logic between transaction handlers into helper functions to reduce duplication
* Provides basic test automation covering both happy path and expected failure scenarios
* The `CommitmentCache` tracks commitment status and maintains stake/pledge relationships
* Added the cache service to `service_senders` for node-wide accessibility
* Extracted common validation logic between …
> feat: commitment tx ingress, validation and caching

- crates/chain/tests/multi_node/sync_chain_state.rs
Reduces `heavy_sync_chain_state` test run time by ~15%. Achieved by mining less block and node shutdown in parallel.
N/A
**Checklist**
> test: reduce test run time for heavy_sync_chain_state

- crates/chain/tests/multi_node/sync_chain_state.rs
Avoid test networks talking to each other across different tests running in parallel.
Port randomisation will be a more robust solution in future and may also need to apply to some of the gossip tests.
Hard coded test ports changed from 8080/8081 to 8078/8079 for sync_heavy_chain_state test
**Checklist**
Port randomisation will replace this hard coding in future
> test: change hardcoded ports from 8080/8081 to 8078/8079

- crates/actors/src/block_index_service.rs
- crates/chain/src/chain.rs
- crates/database/src/block_index_data.rs
This PR significantly improves the genesis block initialization process by consolidating logic into a single source of truth and eliminating the separate genesis initialization thread.
* **Unified Genesis Provisioning**: Created a streamlined `get_or_create_genesis_info` function that handles genesis block and commitment transaction provisioning across all node modes. 
* Removes the need to write genesis headers to disk to pass between threads.
* **One thread instead of two**: Eliminated the separate genesis initialization thread in favor of the main services thread
* Provides direct access to genesis header and commitments provisioned during genesis init to be easily referenced by services during initialization.
* Now only initialize `irys_db` and `block_index` once and pass them around …
> feat: simplify node initialization paths

- .gitignore
- Cargo.lock
- Cargo.toml
- crates/actors/Cargo.toml
- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/chain/Cargo.toml
- crates/chain/src/chain.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/multi_node/sync_chain_state.rs
- crates/reward-curve/Cargo.toml
- crates/reward-curve/src/lib.rs
- crates/reward-curve/src/main.rs
- crates/types/src/block.rs
- crates/types/src/config.rs
- crates/types/src/serialization.rs
- crates/types/src/storage_pricing.rs
- xtask/src/main.rs
- added logarithmic decay block reward function
- block producer & pre-validation will use this block reward curve to calculate the reward
- tests that ensure that the math follows reference implementation
- added executable to simulate block reward emissions, `cargo xtask emission-simulation`:
- (for plotting purposes)  The goal of this is just to ensure that the emission curve & the generated data match visually of what's expected.
- config has a new parameter to account for "reward address"
- added a block reward shadow that updates the miners balance
#366
**Checklist**
> feat: block rewards for miners

- crates/actors/src/epoch_service/epoch_replay_data.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/utils.rs
- crates/database/src/db.rs
Adds a more robust epoch block replay test that validates that a node can be restarted and the epoch state deterministically recreated.
**Checklist**
> more robust epoch_service replay tests

- crates/actors/src/packing.rs
- crates/cli/src/main.rs
- adds `yield_now` calls to packing, so that the packing actor (& the node) can shutdown when there are still packing requests
- tweaks the logging for the irys CLI's account dump command to include the filename
This is a second small set of changes from testnet I forgot to upstream earlier
> feat: more misc testnet fixes

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/utils.rs
fix: the BlockPrevalidatedMessage timing & mine_blocks_exact()
* Fixed a critical bug in `block_discovery` where `BlockPrevalidatedMessage` was being sent prematurely, before prevalidation was actually complete
* Implemented a deterministic test utility method `mine_blocks_exact(num_blocks)` that guarantees exactly the requested number of blocks are mined, handling the probabilistic nature of mining by automatically discarding additional solutions
Fixes #[issue-number] (please replace with actual issue number)
The timing bug in block prevalidation could potentially lead to race conditions where invalid blocks were processed as if they had passed validation. The new test method should make our testing more reliable by eliminating flakiness caused by variable block production.
> fix: the BlockPrevalidatedMessage timing & mine_blocks_exact()

- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/commitment_cache.rs
- crates/actors/src/mempool_service.rs
- crates/chain/src/chain.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
This PR refactors how we handle storage modules to enable runtime modifications:
* Replaces the current approach of cloning `Vec<Arc<StorageModule>>` to different actors/services with a global `ReadGuard` pattern
* Introduces `StorageModulesReadGuard` to:
* Clearly communicate code locations with permission to update the global storage module list
* Simplify parameter types from complex nested generics (`Arc<RwLock<Vec<Arc<StorageModule>>>>` or `RwLockReadGuard<'_, Vec<Arc<StorageModule>>>`) to a single readable type
* Centralizes ownership of storage module membership into a single global list that can be modified at runtime
Addresses #[issue-number] (please update with actual issue number)
This PR is part of a larger effort to enable dynamic storage module management:
* A companion …
> feat: make storage_modules list updateable behind RwLock

- crates/types/src/simple_rng.rs
This PR adds [unbiased RNG clamping logic](https://stackoverflow.com/a/10984975) to the SimpleRNG used for partition assignments
This means genesis initialisations with the same last epoch hash and different storage module counts will no longer have the strange behaviour of having identical hashes for most storage module counts.
> fix: introduce unbiased clamping logic

- Cargo.lock
- Cargo.toml
- crates/actors/Cargo.toml
- crates/actors/src/mempool_service.rs
- crates/chain/tests/multi_node/mempool_tests.rs
- crates/chain/tests/multi_node/mod.rs
- crates/chain/tests/utils.rs
- crates/types/src/chunk.rs
* Adds support for uploading chunks ahead of their `data_root` arriving in a transaction.
* Chunks are held in a pending LRU cache
* When the transaction arrives it attempts to flush the cache
* Added some test methods "post_storage_tx()" and made `start_public_api` return its actix app 
**Checklist**
> feat: allow chunks to be uploaded ahead of their transactions

- crates/chain/src/chain.rs
- crates/chain/src/peer_utilities.rs
- crates/chain/tests/api/external_api.rs
- crates/p2p/src/gossip_service.rs
`sync_state_from_peers` now ~15s faster. Removed hard coded delay. Replace with fn that polls VDF service until `global_step >= desired_step`, with a 30s timeout.
`heavy_external_api()` now faster with less boiler plate.
N/A
**Checklist**
N/A
> perf: wait for desired vdf step + test speed improvements

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/broadcast_mining_service.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/epoch_service/epoch_service.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/mining.rs
- crates/actors/src/packing.rs
- crates/actors/src/storage_module_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/multi_node/peer_mining.rs
- crates/chain/tests/utils.rs
- crates/storage/src/chunk_provider.rs
- crates/storage/src/storage_module.rs
* Added span logging to enhance traceability across the following actors & services:
* EpochService 
* BlockDiscovery + block_validation module
* BlockProducer
* BroadcastMiningService
* PartitionMiningActor
* Made `StorageModule::partition_assignment` thread-safe by wrapping `Option<PartitionAssignment>` in an `RwLock`
* This enables safe runtime updates to partition assignments through `Arc<StorageModule>` references in the global storage modules vector
* Allows dynamic assignment of partitions without requiring full module recreation
* Pre-initialize packing and mining actors for all storage modules at startup, including unassigned ones
* Unassigned actors remain idle until activated by partition assignment
* Simplifies the activation process when partition hashes are assigned during …
> feat: peer_mining test unblocked + logging spans

- crates/chain/tests/multi_node/peer_mining.rs
- crates/storage/src/storage_module.rs
Ensures that the `packing_params.toml` in each submodule is updated when a `partition_hash` is assigned.
**Checklist**
> feat: update submodule packing_params.toml with partition assignment

- crates/actors/src/epoch_service/epoch_service.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/testing-utils/src/utils.rs
A test where the genesis node mines an epoch block with no commitments and the peer processes it.
> feat: add a test for peers processing empty epoch blocks

- crates/types/Cargo.toml
- crates/types/src/h256.rs
- crates/types/src/lib.rs
- crates/types/src/serialization.rs
This PR pulls out the expanded version of the construct_fixed_hash! macro to replace Debug and Display to use base58 formatting.
> feat: pull out H256 and update the Debug and Display implementations

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/commitment_cache.rs
- crates/actors/src/ema_service.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/services.rs
- crates/actors/src/validation_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/utils.rs
- crates/database/src/block_index_data.rs
- crates/p2p/src/gossip_service.rs
- crates/p2p/src/server_data_handler.rs
- crates/types/src/gossip.rs
* converts the `block_tree_service` to a tokio actor
* adds the plumbing for a tokio::broadcast channel for reorg messsages
* adds plumbing for the mempool to subscribe to said messages
* adds a `ReorgEvent` that contains state about the reorg broadcast
* adds some tests to `block_tree` just to validate the inner implementation
> feat: detect and broadcast reorgs

- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/utils.rs
allow `wait_for_reorg()` to subscribe to the reorg event and return a future (which can be awaited after causing a reorg).
Taking this approach fixes the `heavy_fork_recovery` test which became flakey after VDF FF made reorgs happen quicker than `wait_for_reorg()` could subscribe to them.
> fix: heavy_fork_recovery test

- crates/chain/tests/promotion/data_promotion_basic.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/utils.rs
- Add methods, reduce code repetition. Make it easier to reason with test cases.
- wait_for_chunk()
- wait_for_confirmed_txs()
- wait_for_ingress_proofs()
- Highlights a 40 second test delay in heavy_double_root_data_promotion_test() where loops are running but never erroring on timeout. Added FIXMEs
Part of https://github.com/Irys-xyz/irys/issues/428
> chore: wait_for_chunk() wait_for_confirmed_txs() wait_for_ingress_proofs()

- Cargo.lock
- crates/actors/Cargo.toml
- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/services.rs
- crates/actors/src/validation_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/utils.rs
- crates/efficient-sampling/src/lib.rs
- crates/irys-reth/src/evm.rs
- crates/vdf/src/lib.rs
- crates/vdf/src/state.rs
- crates/vdf/src/vdf.rs
- crates/vdf/src/vdf_utils.rs
- Rewrote validation_service.rs to use tokio instead of actors
- Added system tx validation logic in block_validation.rs
- Updated block_producer.rs to use common systx builders
⚠️ The validation for system txs is incomplete because I don't yet fetch the sytem txs for the incoming block. Awaiting on other work. Will be done in future pr.
⚠️ No unittests for catching invalid system txs becuase the core functionality is mocked for the time being (ignoring failing errors), all system txs are deemed valid from the validation serviec perspective.
**Checklist**
> feat: add valdiator for system txs inside validation_service

- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/ema_service.rs
- crates/actors/src/mempool_service.rs
- crates/api-server/src/routes/block.rs
- crates/api-server/src/routes/index.rs
- crates/chain/tests/ema_pricing/ema_pricing.rs
- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/startup/startup.rs
- crates/chain/tests/utils.rs
Replaces the terribly overloaded tuple in the block tree with a proper struct with field names.
> feat: replace block_tree entry tuple with struct

- crates/actors/src/ema_service.rs
- crates/chain/src/chain.rs
- ema service listents to a reorg event
- every time it receives a reorg event, it will recalculate its state from the canonical chain
**Checklist**
> feat: reorg support for ema service

- crates/chain/tests/api/api.rs
- crates/chain/tests/api/client.rs
- crates/chain/tests/api/tx.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/utils.rs
- Replace incorrect call to `self.node_ctx.set_partition_mining(false)` with `self.node_ctx.stop_mining().await`
- removed dead code
- added tracing
- enforced named test folder isolation
N/A
**Checklist**
N/A
> fix: util method fixes and test improvements

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_tree_service/test_utils.rs
- crates/actors/src/ema_service.rs
- crates/actors/src/lib.rs
- crates/actors/src/mempool_service.rs
- crates/actors/src/validation_service/active_validations.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/utils.rs
- crates/database/src/commitment_snapshot.rs
- crates/database/src/lib.rs
- crates/p2p/src/block_status_provider.rs
move the refactored `CommitmentSnapshot` out of the `actors` crate and into `database` because it's no longer an actor or service but a data model.
> fix: move commitment_snapshot.rs out of actors and into database

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/mempool_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/mod.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/api/tx_duplicates.rs
- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/multi_node/mempool_tests.rs
- crates/chain/tests/utils.rs
- crates/database/src/commitment_snapshot.rs
**Changes**
* Streamline and add checks to `tx_commitments.rs` test
* Add duplicate detection for commitment transactions (stake/pledge) and submit ledger transactions in block discovery
* Filter `getBestMempoolTx` to only include pending transactions not present in canonical chain
* Rename `post_storage_tx` test to `post_data_tx` for clarity
* Fix bug in `CommitmentSnapshot::get_commitment_status()` that incorrectly returned `Unstaked` for pledge commitments when address was staked in prior epoch
* Refactor test methods to use HTTP client instead of actix app reference
* Add test context methods for posting chunks
* Remove dead code for rolling back commitments from `CommitmentSnapshot`
* adds new `tx_duplicates.rs` test
**Additional Context:**
Publish transaction validation is not …
> feat: handle duplicate transactions in mempool and block discovery

- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/api/tx_duplicates.rs
- crates/chain/tests/utils.rs
- crates/packing/src/lib.rs
- xtask/src/main.rs
This PR modifies xtask/xshell to strip problematic cargo env vars that are set when xtask is run as a cargo subcommand.
These env vars trigger unnecessary rebuilds of the `ring` crate, which is a pretty deep dependency, when switching from xtask to cargo check, for example.
This PR also changes CI to run clippy check on tests, and resolves some lingering lint violations left by the absence of this check.
see https://github.com/oxidecomputer/omicron/pull/7740 for more information, as this is exactly the problem we're having
> fix: strip problematic env vars from xtask subcommands

- crates/actors/src/block_discovery.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_tree_service/test_utils.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/epoch_service/commitment_state.rs
- crates/actors/src/epoch_service/epoch_replay_data.rs
- crates/actors/src/epoch_service/epoch_service.rs
- crates/actors/src/epoch_service/epoch_service_messages.rs
- crates/actors/src/epoch_service/partition_assignments.rs
- crates/actors/src/mempool_service/commitment_txs.rs
- crates/actors/src/mempool_service/inner.rs
- crates/actors/src/mempool_service/mod.rs
- crates/actors/src/services.rs
- crates/actors/src/validation_service.rs
- crates/actors/src/validation_service/active_validations.rs
- crates/actors/src/validation_service/block_validation_task.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/multi_node/fork_recovery_epoch.rs
- crates/chain/tests/multi_node/mod.rs
- crates/chain/tests/multi_node/peer_mining.rs
- crates/chain/tests/utils.rs
- crates/database/src/data_ledger.rs
- crates/p2p/src/block_status_provider.rs
- crates/types/src/config.rs
The `epoch_service` was not fork-aware, which caused issues because each fork can have its own `epoch_state` with distinct pledges, commitments, and partition assignments. Simply storing the canonical `epoch_state` in an `epoch_service` was insufficient for validating blocks on forks or handling reorgs gracefully.
**Architecture Change**: This PR refactors the `epoch_service` state into `epoch_snapshot` objects owned by the `block_tree`. When adding blocks to the `block_tree`, callers must now provide an `epoch_snapshot`:
- **Standard blocks**: Copy the parent's `Arc<EpochSnapshot>` (90% of cases)
- **Epoch blocks**: Apply commitments from the epoch block to create a new snapshot
- **Tests**: Use the new `dummy_epoch_snapshot()` utility for non-epoch-aware tests
**Lock Removal**: …
> feat: replace the epoch_service with epoch_snapshots on the block_tree

- crates/chain/tests/api/client.rs
- crates/chain/tests/block_production/analytics.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/ema_pricing/ema_pricing.rs
- crates/chain/tests/multi_node/mempool_tests.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/chain/tests/utils.rs
- Remove many uses of deprecated `mine_block()` fn in favour of `mine_block()` method.
- ~Improve stability of `heavy_test_always_build_on_max_difficulty_block()`~ see https://github.com/Irys-xyz/irys/issues/519
**Checklist**
> chore: test utils cleanup mine_block() usage

- crates/chain/tests/multi_node/fork_recovery.rs
- crates/chain/tests/utils.rs
- New test util method: `get_balance()` to retrieve reth balance on a node for a specific address at a specific block
- New test scenario
- Test scenario for three nodes, mining to three different heights in isolation from one another
- submit/publish txs are created on canonical chain and seen to remain canonical
- submit/publish txs are created on a non canonical chain and are seen to be reverted before inclusion in a later canonical block
- Test for correct balances after each mined block, and after reorgs that bring all three nodes into sync
submit/publish txs are currently hard coded to have a fee of 1. This is outside the scope of this PR to correct this, but the PR is a good stepping stone to get there.
> test: reorg publish txs test across 3 nodes and multiple forks

- crates/actors/src/block_validation.rs
- crates/actors/src/epoch_service/epoch_service.rs
- crates/actors/tests/epoch_service_tests.rs
Removes the `Arc<RwLock<..>>` from `EpochSnapshot::PartitionAssignments` as epoch snapshots are only mutated during initialization.
> fix: Remove the obsoleted RwLock from PartitionAssignments

- crates/actors/src/reth_service.rs
- crates/chain/src/chain.rs
- crates/p2p/src/sync.rs
This PR incorporates a hotfix from testnet for a case where the trusted fast sync was interrupted, and Reth was a block behind. This caused the testnet peer to crash loop, due to the FCU created during startup. The fix was to explicitly invoke `repair_missing_payloads_if_any` before sending the initial FCU, to allow the system to recover.
This PR also includes some logging tweaks.
**Checklist**
~~- [ ] Tests have been added/updated for the changes.~~ NB: testing for this case has been backlogged #533
> fix: repair payloads before sending an FCU on startup

- Cargo.lock
- crates/actors/src/addresses.rs
- crates/actors/src/block_producer.rs
- crates/actors/src/mining.rs
- crates/actors/src/services.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/chain/Cargo.toml
- crates/chain/src/chain.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/block_production/reset_seed.rs
- crates/chain/tests/external/block_production.rs
- crates/chain/tests/multi_node/validation.rs
- crates/chain/tests/utils.rs
- crates/irys-reth/Cargo.toml
- crates/irys-reth/src/lib.rs
- crates/reth-node-bridge/src/adapter.rs
- crates/reth-node-bridge/src/node.rs
- crates/types/src/arbiter_handle.rs
- block producer is now a tokio service
- block producer does not use the reth-test-helper adapter because some methods are not Send when using it
- main culprit was when interacting with the payload helper - instead the logic has been hoisted out & embedded into block producer (logic for building a payload, submitting to reth)
- all interactions with block producer are done via channels
- refactor of `slow_heavy_reset_seeds_should_be_correctly_applied_by_the_miner_and_verified_by_the_peer` test - previous implementation made a lot of false assumptions about vdf speed, and how many checkpoints are included in a block. it made the test non-deterministic.
**Checklist**
> feat: block producer as a tokio service

- Cargo.lock
- crates/api-server/src/routes/post_version.rs
- crates/p2p/src/peer_list.rs
- crates/p2p/src/sync.rs
- crates/p2p/src/tests/block_pool/mod.rs
- crates/types/Cargo.toml
- crates/types/src/peer_list.rs
This PR fixes an issue that causes the node to ignore multiple hansdhake requests from the same peer if the peer information hasn't changed. This PR introduces a p2p handshake cooldown. If additional handshake is made during cooldown period, it's going to be ignored. If it's made after the cooldown, it's going to be handled as if the peer information has been updated
**Checklist**
> feat: handshake cooldown

- crates/p2p/src/gossip_client.rs
- crates/p2p/src/gossip_service.rs
- crates/p2p/src/server_data_handler.rs
This PR spawns a task for each broadcast, so multiple broadcasts of the same data can run in parallel
**Checklist**
> feat: make gossip broadcasts detached from the main broadcast thread

- crates/p2p/src/gossip_client.rs
- crates/p2p/src/peer_list.rs
This PR adds decreasing of a peer score if get_data request failed, as well as better score handling and client structure in general
**Checklist**
> fix: decrease peer score on unsuccessful data request

- Cargo.lock
- crates/api-client/Cargo.toml
- crates/api-client/src/lib.rs
- crates/api-server/src/lib.rs
- crates/api-server/src/routes/index.rs
- crates/api-server/src/routes/peer_list.rs
- crates/api-server/src/routes/post_version.rs
- crates/chain/src/chain.rs
- crates/domain/Cargo.toml
- crates/domain/src/models/mod.rs
- crates/domain/src/models/peer_list.rs
- crates/p2p/src/block_pool.rs
- crates/p2p/src/execution_payload_provider.rs
- crates/p2p/src/gossip_client.rs
- crates/p2p/src/gossip_service.rs
- crates/p2p/src/lib.rs
- crates/p2p/src/peer_list.rs
- crates/p2p/src/server.rs
- crates/p2p/src/server_data_handler.rs
- crates/p2p/src/sync.rs
- crates/p2p/src/tests/block_pool/mod.rs
- crates/p2p/src/tests/integration/mod.rs
- crates/p2p/src/tests/util.rs
- crates/p2p/src/types.rs
This PR is intended to be the first one out of several PRs that are breaking down `PeerListService` into smaller pieces. This PR:
- Creates a `PeerListGuard` structure, and moves it to the domain crate
- Removes all data access functionality from the `PeerListService`
- Removes `PeerListFacade` traits and related error types
- Creates a tokio channel that serves as a plug between new `PeerListGuard` and old `PeerListService` without changing how `PeerListService` works internally - i.e, without removing actix
**Checklist**
> feat: peer list breakdown

- crates/actors/src/mempool_service/inner.rs
- crates/chain/tests/block_production/block_production.rs
- crates/types/configs/testnet.toml
- crates/types/src/config.rs
- Introduce commitment tx limit per block.
- epoch blocks are unaffacted by this PR as `block_producer` does not use the returned commitment txs from mempool's `handle_get_best_mempool_txs`
- test added to confirm commitment txs rollover as expected
**Checklist**
> fix: introduce commitment tx limit per block

- Cargo.lock
- crates/actors/src/block_validation.rs
- crates/actors/src/mempool_service/mod.rs
- crates/actors/src/mempool_service/pledge_provider.rs
- crates/actors/tests/epoch_service_tests.rs
- crates/api-server/src/lib.rs
- crates/api-server/src/routes/price.rs
- crates/chain/src/chain.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/chain/tests/api/tx_duplicates.rs
- crates/chain/tests/block_production/block_production.rs
- crates/chain/tests/multi_node/mempool_tests.rs
- crates/chain/tests/startup/auto_stake.rs
- crates/chain/tests/utils.rs
- crates/config/templates/testnet_config.toml
- crates/database/Cargo.toml
- crates/database/src/system_ledger.rs
- crates/domain/src/snapshots/commitment_snapshot.rs
- crates/primitives/src/commitment.rs
- crates/testing-utils/Cargo.toml
- crates/testing-utils/src/utils.rs
- crates/types/Cargo.toml
- crates/types/src/config.rs
- crates/types/src/transaction.rs
- when constructing pledge/unpledge txs we need to know the count of how many pledges a user has. Previous implementation did not acocunt for txs in the mempool. This PR fixes that
- Added API endpoint for getting commitment tx fees
- Fees field gets populated on CommitmentTransactions 
- Updated config to have static commitment tx processing fees (expressed in Irys)
**Checklist**
What this PR does **not** do:
- validation on the mempool is not part of this PR
- accounting for the fees on reth side is not part of this PR
> feat: fees for commitment txs & mempool aware pledge counter

- crates/actors/src/block_producer.rs
- crates/actors/src/block_validation.rs
- crates/actors/src/lib.rs
- crates/actors/src/shadow_tx_generator.rs
- crates/chain/tests/block_production/block_production.rs
- crates/irys-reth/src/evm.rs
- crates/irys-reth/src/lib.rs
- crates/irys-reth/src/shadow_tx.rs
- switched to using Eip1559 txs for shadow txs - they allow specifying the fee that must be given to the miner in the tx itself.
- During shadow tx processing give the fee to the miner of the block
- The fee is now provided by irys during shadow tx construction
- irys-reth will enforce that block rewards do not distribute fees
**Checklist**
> feat: commitment shadow txs pay fees to the miner

- Cargo.lock
- crates/chain/Cargo.toml
- crates/chain/src/main.rs
- crates/testing-utils/Cargo.toml
- crates/testing-utils/src/utils.rs
This PR adds a custom color-eyre wrapping panic hook that prints timestamps before the color-eyre hook runs, so that we get timestamps with our panics.
> feat: add custom timestamping panic hook

- crates/database/src/db.rs
- database commits will no longer occur if f() errors in `update_eyre()` or `view_eyre()`
**Checklist**
> fix: prevent commit, via early return from f() if Err returned

- crates/p2p/src/sync.rs
This PR adds a simple progress/time based exit condition to `wait_for_processed_block_to_reach_target`
this works by resetting a 60s timer every time the highest processed block increases - if the timer expires, `sync_chain` early exits. This is to prevent cases where a node can't sync a chain causing the node to hang indefinitely.
> feat: add a progress/time based exit condition for `wait_for_processed_block_to_reach_target`

- crates/actors/src/mempool_service/chunks.rs
- crates/actors/src/mempool_service/inner.rs
- crates/chain/tests/external/api.rs
- crates/chain/tests/external/programmable_data_basic.rs
- crates/chain/tests/multi_node/mempool_tests.rs
- crates/chain/tests/utils.rs
- crates/database/src/database.rs
- crates/database/src/tables.rs
- crates/types/src/ingress.rs
This PR changes the IngressProof table into a DupSort table.
This is done so we can have multiple address -> ingress proof stored under a single DataRoot key, and allows for easier management and ingress proof collection.
**Checklist**
> feat: change the IngressProofs table to be a DupSort table

- crates/api-server/src/routes/block_index.rs
- impose MAX_BLOCK_INDEX_QUERY_LIMIT on /v1/block_index
- currently set to 1000 blocks
**Checklist**
> fix: impose MAX_BLOCK_INDEX_QUERY_LIMIT on /v1/block_index

- crates/actors/tests/epoch_snapshot_tests.rs
- crates/database/src/system_ledger.rs
- crates/domain/src/snapshots/epoch_snapshot/epoch_snapshot.rs
When backfilling ledger slots with capacity partition hashes, the epoch snapshot now operates on a subset of the set of all assigned capacity partitions that excludes any partition_hashes assigned to miners that already have a partition assigned to the slot.
Adds a test method to stake and pledge additional signers in the genesis block (@JesseTheRobot , this might be useful configuring testnet)
Also adds a test to ensure `mining_address` uniqueness is being enforced per slot.
Note: as this new strategy for picking a random capacity partition from the subset of all capacity partitions changes the picking order, we have broken determinism from the old partition assignment strategy and the partition_determinism_test is updated to enshrine the new sequence.
> feat: make slot partition assignments require unique mining addresses

- crates/actors/src/data_sync_service.rs
- crates/actors/src/data_sync_service/chunk_orchestrator.rs
- crates/actors/src/storage_module_service.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/domain/src/models/storage_module.rs
- crates/domain/src/snapshots/epoch_snapshot/epoch_snapshot.rs
Make sure storage modules preserve their `partition_hash` assignments across Capacity/DataLedger re-assignments.
> fix: storage module partition hash should persist across Capacity/Ledger reassignments.

- crates/chain/src/main.rs
- crates/domain/src/models/chain_sync_state.rs
- crates/p2p/src/chain_sync.rs
This PR adds a new flag to the syncing service that used to mark that the sync task has been spawned. This is different from is_syncing flag in the sync state, which is set to true by the syncing task after it determines that there are blocks that are available for syncing.
**Checklist**
> feat: internal is syncing flag

- crates/actors/src/block_tree_service.rs
- crates/actors/src/cache_service.rs
- crates/chain/src/chain.rs
- crates/chain/tests/integration/cache_service.rs
- crates/chain/tests/promotion/data_promotion_double.rs
- crates/database/src/database.rs
- crates/database/src/db_cache.rs
- crates/domain/src/snapshots/epoch_snapshot/epoch_snapshot.rs
* only expire data_roots and IngressProofs from the cache when the blocks that added them expire out of the submit ledger
* remove `timestamp` from the `CachedDataRoot` struct as it wasn't used, expiry is based on block_height
* update tests accordingly
> feat: prune CachedDataRoots at submit ledger term expiry

- crates/chain/src/chain.rs
- crates/chain/src/main.rs
- crates/chain/src/utils.rs
- crates/chain/tests/block_production/reset_seed.rs
- crates/chain/tests/multi_node/sync_chain_state.rs
- crates/chain/tests/utils.rs
- crates/config/templates/testnet_config.toml
- crates/p2p/src/chain_sync.rs
- crates/types/src/config.rs
To allow genesis node to perform fast sync on restart, `NodeMode` has been separated into two: `NodeMode` and `SyncMode`
**Checklist**
> feat: separate sync and node mode

- Cargo.lock
- crates/chain/src/main.rs
- crates/cli/Cargo.toml
- crates/cli/src/main.rs
Adds a `rollback-blocks` command to the CLI, which just removes the provided number of blocks from the block index, after backing it up.
> feat: CLI rollback-blocks command

- crates/domain/src/models/execution_payload_cache.rs
- crates/p2p/src/block_pool.rs
- crates/p2p/src/tests/integration/mod.rs
Payload repair process might fail if the payload is in the cache, but not in reth. This PR changes payload search to only include reth.
**Checklist**
> fix: during payload repair don't consider payload existing if it is in the cache

- crates/p2p/src/chain_sync.rs
This PR adds special case when running a node in Genesis mode with sync mode send to Trusted, so the genesis will continue a normal startup sequence if there's nobody else in the network
**Checklist**
> feat: add a special case for the genesis node so it doesn't exit if it's in a trusted sync mode and can't fetch the index

- crates/chain/tests/multi_node/sync_chain_state.rs
- crates/chain/tests/utils.rs
- Reworked the peer discovery so we deterministly send peer info between peers. This seems result in a more stable test but is also not a solution to the underlying problem.
- Added some retry logic for malformed json, should that ever occur.
**Checklist**
> test: stability slow_heavy_sync_chain_state_then_gossip_blocks

- Cargo.lock
- crates/chain/tests/mod.rs
- crates/chain/tests/partition_assignments/mod.rs
- crates/chain/tests/partition_assignments/sm_reassignment_tests.rs
- crates/domain/src/models/storage_module.rs
- crates/testing-utils/Cargo.toml
- crates/testing-utils/src/utils.rs
Make sure we can restart a node after partitions have been reassigned multiple times.
(Adds a test for this scenario)
> feat: add storage module reassignment and restart integration test

- crates/types/src/signature.rs
Improve error handling of `from_base58` failures. Now return a serde error rather than panic.
**Checklist**
> fix: return serde error instead of expect/panic

- crates/actors/src/mempool_service.rs
- crates/actors/src/mempool_service/commitment_txs.rs
- crates/api-server/src/routes/commitment.rs
- crates/api-server/src/routes/tx.rs
- crates/chain/tests/api/tx_commitments.rs
- crates/p2p/src/types.rs
Before this PR commitment, transactions were not checked for sufficient funding.
This PR adds:
- a `validate_funding` method to check the balance
- an additional `BalanceFetchError` variant for TxIngressError
- and logic to use the previous to check balance proir to including the tx in the mempool
**Checklist**
> fix: Added funding check for commitment txs

- crates/types/src/merkle.rs
Avoid confusing variable name. `max_byte_range` renamed to `pivot_note`
**Checklist**
> fix: max_byte_range becomes pivot_note for clarity

- .github/workflows/rust.yml
adds explicit tags to "misc" runners & jobs so that they don't run on the limited number of test-runner instances
> chore: don't run misc tasks on test runner instances

- crates/domain/src/models/storage_module.rs
Improve write throughput by only updating the on-disk intervals file & calling fsync per-batch, instead of per-chunk.
Performance went from `sync_pending_chunks took 33.680s for 500` to `sync_pending_chunks took 0.969s for 750`
> feat(storage_module): Improve write throughput

- crates/actors/src/block_tree_service.rs
- crates/actors/src/block_validation.rs
**Before this PR**, there was a race condition in the block validation scheduling process where blocks were sent for validation before being marked as scheduled in the cache. This might lead to an inconsistent state if the validation service processed the block before the cache was updated.
**This PR** fixes the race condition by reordering operations to mark blocks as "validation scheduled" in the cache before sending them to the validation service.  Additionally, it adds proper error handling for cache update failures by introducing a new `UpdateCacheForScheduledValidationError` variant and returning early if marking the block fails, preventing the validation message from being sent when the cache state is inconsistent.
Please link to the issue(s) that will be …
> fix: mark scheduled validation before scheduling

- crates/types/src/merkle.rs
Fixes a gap in `validate_path` where `target_offset` was only used to choose left/right traversal but not validated against the final leaf range.
Unit tests added:
- validate_path_rejects_above_right_bound()
- validate_path_accepts_in_bounds_edges() 
**Checklist**
> fix: validate_path() now validates target_offset

- crates/p2p/src/gossip_client.rs
- crates/p2p/src/gossip_service.rs
- crates/p2p/src/peer_network_service.rs
- crates/p2p/src/server.rs
- crates/types/src/config/node.rs
This PR spawns a new task for each new gossip broadcast. Also, not p2p parameters can be configured through the config file.
**Checklist**
> feat: remove throttling on the p2p broadcasts on large sets of peers

- crates/actors/src/block_tree_service.rs
- crates/actors/src/chunk_migration_service.rs
- crates/actors/src/services.rs
- crates/chain/src/chain.rs
* Converts the `ChunkMigrationService` to a tokio service. 
* Improves the parameters of the `BlockMigrated` message to scale to multiple data ledgers.
> feat: migrate chunk_migration_service to tokio service

- crates/types/src/peer_list.rs
- Fixes a decoding bug where `PeerListItem::from_compact` only advanced 8 bytes for `last_seen` but did not advance when the optional `is_online` byte was present, causing the returned remainder to incorrectly include the boolean.
- Update: track `total_consumed` and increment when `is_online` exists; default `is_online` to `false` when absent 
- Documentation: PeerListItem::from_compact() documentation added. Comments corrected in decode_address()
- Adds tests:
- Ensures round-trip decode leaves no remainder.
- Ensures decode works when the optional `is_online` byte is missing (no remainder, `is_online=false`).
**Checklist**
> fix: buffer advancement for optional is_online in PeerListItem::from_compact

- Cargo.lock
- crates/actors/src/mining.rs
- crates/efficient-sampling/Cargo.toml
- crates/efficient-sampling/src/lib.rs
Before this PR:
The num_recall_ranges_in_partition function used floor division (/), which caused the last chunks in a partition to be ignored when the partition size wasn't evenly divisible by the recall range size. For example, with 1000 chunks per partition and 800 chunks per recall range, the function would return one recall range, leaving the last 200 chunks unreachable. 
This PR:
- Changes num_recall_ranges_in_partition to use ceiling division (div_ceil), ensuring all chunks in a partition are covered by recall ranges
- The fix ensures that when num_chunks_in_partition is not evenly divisible by num_chunks_in_recall_range, the result rounds up to include a final partial range covering the remaining chunks
- Example: 1000 chunks / 800 chunk ranges now …
> fix(efficient sampling): using ceiling calculation for recall ranges

- crates/api-server/src/routes/price.rs
- crates/chain/src/peer_utilities.rs
- crates/types/src/block.rs
- crates/types/src/version.rs
**Before this PR:**
u64 fields in API responses and type definitions were serialised as numbers, which could cause precision loss or overflow issues in JavaScript clients when values exceeded JavaScript's safe integer limit (2^53 - 1). This created potential compatibility issues for frontend applications consuming the API.
**This PR:**
Implements string serialisation for u64 fields across the codebase using the `string_u64` serde module, ensuring that large integer values are safely transmitted as strings in JSON responses while maintaining backwards compatibility.
- Updated `PriceInfo` struct in `routes/price.rs` to serialise `bytes` field as string
- Added comprehensive tests for u64 serialisation in price endpoints
- Applied `string_u64` serialisation to …
> fix(types): added string u64 serialization to u64 fields

- crates/actors/src/block_validation.rs
- crates/actors/src/mempool_service.rs
- crates/chain/tests/promotion/promotion_with_multiple_proofs.rs
Makes sure we can still promote even when there's less miners than the consensus # of proofs required to promote. (important for early bootstrapping of the network)
> feat: allow promotions when miner count < required proofs

- Cargo.lock
- crates/database/src/data_ledger.rs
- crates/domain/Cargo.toml
- crates/domain/src/models/block_tree.rs
- crates/domain/src/snapshots/commitment_snapshot.rs
- crates/domain/src/snapshots/epoch_snapshot/commitment_state.rs
- crates/domain/src/snapshots/epoch_snapshot/epoch_snapshot.rs
- crates/domain/src/snapshots/epoch_snapshot/partition_assignments.rs
- crates/types/src/partition.rs
- crates/types/src/signature.rs
- crates/types/src/transaction.rs
Add super basic Hashing for commitment & epoch snapshots for easier debugging (so it's easier to tell if there's a state mismatch)
This is primarily meant as an aid to track down the behaviour observed on testnet, but I suspect it'll have some utility beyond that given how complex the data model is.
> feat: add basic Hashing for commitment & epoch snapshots for easier debugging

- crates/types/src/ingress.rs
- crates/types/src/merkle.rs
- crates/types/src/transaction/fee_distribution.rs
`generate_ingress_proof_tree()` and `generate_ingress_proof()` now accept slice without ownership.
- avoids cloning the proof
- accepts owned or borrowed arg
Completes https://github.com/Irys-xyz/irys/issues/847
Performance improvement suggested in https://github.com/Irys-xyz/irys/pull/786 review
**Checklist**
> perf: generate_ingress_proof_tree() and generate_ingress_proof() now accept slice
